Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: techno-secret-rds-credentials
      Description: Secret storing RDS Credentials
      SecretString: '{"host": "blank","name":"ordersdb","username":"dbadmin","password":"TechnoCloud2026!"}'
      Tags:
        - Key: Name
          Value: AppB          

  Rotation:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: Secret 
    Properties:
      SecretId: !Ref Secret
      RotationRules:
        ScheduleExpression: 'rate(30 days)'